export const header = document.querySelector(".header")
export const footer = document.querySelector(".footer")
export const thanksSection = document.querySelector('.thanks')
export const thanksTitle = document.querySelector('.thanks__title')
export const counterItems = document.querySelectorAll('.counter .item--standart')
export const observerCounterItems = document.querySelectorAll('.counter .item--observer')